print("Hello World, I'm Python.... What's your name?")
name=input()
print("Nice to meet you, ", name)
print("It is really simple to do scripting with me... But I can do a lot of things.... \nLet me show you\nI can add two numbers and give you the result\nGive me one number")
number1=input()
print("Number:", number1)
print("Give me another number")
number2=input()
print("Another number:", number2)
addition=float(number1)+float(number2)
print(number1, " + ", float(number2), " = ", addition)
print("Also, I can multiply two numbers and give you the result\nGive me one number")
number11=input()
print("Number: ", number11)
print("Give me another number")
number22=input()
print("Another number:", number22)
print(float(number11), " * ", number22, " = ", multiply)
multiply=float(number11)*float(number22)
print("I can do Boolean operations as well...\nGive me one string")
word1=input()
print("String:", word1)
print("Give me another string")
word2=input()
print("Another string:", word2)
word_operation=word1==word2
print(word1, "is equal to", word2, "?", word_operation)
print("How old are you?")
age=int(input())
print("Age:", age)
five_years=age+5
print("In 5 years you we'll be", five_years, "OMG! You are really old\nC U Next Time :D with more Python")
print("\n")
print("*\n**\n***\n****\n*****\n******\n*******")